version: '3.1'
services:

  postgres:  #по хорошему для каждого сервиса нужен свой отдельный контейнер с БД, но в качестве упрощения тут в рамках
    #одного сервера БД будут созданы разные базы данных - под каждый микросервис
    image: 'postgres:14'
    container_name: postgres_amigos
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    volumes:
      - postgres:/data/postgres
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    ports:
      - '9411:9411'

  pgadmin:
    image: dpage/pgadmin4:4.23
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password

    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin:
