version: '3.1'
services:

  postgres:  #по хорошему для каждого сервиса нужен свой отдельный контейнер с БД, но в качестве упрощения тут в рамках
    #одного сервера БД будут созданы разные базы данных - под каждый микросервис
    image: 'postgres:14'
    container_name: postgres_amigos
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    volumes:
      - postgres:/data/postgres
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  # ------------------------ Данные образы берем из нашего докер репозитрия, куда они попадают через jib. Если их нет, то можно просто запустить соответствующие модули
  eureka-server:
    image: naroru/eureka_server
    container_name: eureka-server
    ports:
      - '8761:8761'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  api-gateway:
    image: naroru/api_gateway
    container_name: api-gateway
    ports:
      - '8087:8087'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: naroru/customer
    container_name: customer
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
  fraud:
    image: naroru/fraud
    container_name: fraud
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq

  notification:
    image: naroru/notification
    container_name: notification
    ports:
      - '8086:8086'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
  # ------------------------
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    ports:
      - '9411:9411'

  pgadmin:
    image: dpage/pgadmin4:4.23
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password

    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin:
