spring:
  application:
    name: notification

server:
  port: 8086

  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  zipkin:
    base-url: http://localhost:9411

    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



