server:
  port: 8087

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER  #name from Eureka
          predicates:
            - Path=/api/v1/customer/** #mask - all request to this address will be redirect to CUSTOMER in Eureka
                                        #may be several

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



